# Generated by Django 3.0.2 on 2020-01-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('author', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('year_of_issue', models.PositiveSmallIntegerField()),
                ('cover', models.CharField(max_length=100)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'highlight',
                'verbose_name_plural': 'highlights',
                'ordering': ('name',),
            },
        ),
    ]
